name: Workflow Pull Request Opened

on:
  pull_request:
    branches: [main]
    types: [assigned, opened, synchronize, reopened]

jobs:
  setup:
    name: preparing
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install packages using yarn.lock
        run: |
          yarn --frozen-lockfile
      - name: Lint check
        run: |
          yarn lint
      - name: Typescript check
        run: |
          yarn tsc
      - name: tests
        run: |
          yarn test:ci
          yarn test:clear
      - name: commit message
        uses: wagoid/commitlint-github-action@v4
