name: Workflow Main - On Push

on:
  push:
    branches: [main]

jobs:
  setup:
    name: preparing
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install packages using yarn.lock
        run: |
          yarn --frozen-lockfile
      - name: Release
        run: |
          yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CI }}
      - name: Prepare publish
        run: |
          yarn prepare-publish
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Prepare publish docs
        run: |
          yarn prepare-publish-docs
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN_CI }}
          publish_dir: ./example/storybook-static
